version: "3.9"

services:

  backend:
    image: "aboger/mbot-backend"
    ports:
      - "3000:8080"


  frontend:
    depends_on:
      - backend
    image: "otoltinova/mbot-frontend"
    ports:
      - "80:80"
