version: "3.9"

services:

  backend:
    image: "aboger/mbot-backend:0.0.1"
    ports:
      - "8080:8080"


  frontend:
    depends_on:
      - backend
    image: "otoltinova/mbot-frontend"
    ports:
      - "80:80"
    environment:
      SERVER_URL: development
